### ISSUE TITLE
edit: edit in emacs

### ISSUE THREAD

**Issue by nico202** [tpapp/julia-repl#22]
When reporting an issue, please provide
in
1. the Emacs version (`M-x emacs-version [RET]`, will also appear in the buffer `*Messages*`),
GNU Emacs 25.3.1 (x86_64-pc-linux-gnu, GTK+ Version 3.22.26) of 2018-01-07

2. the Julia version (`VERSION`)
v"0.6.0"

3. the version of `julia-repl` (something like “latest master” is fine).
julia-repl-20171116.46

4. self-contained steps to replicate the issue.
press C-c c-e (julia-repl-edit) in a julia buffer. nano shows up inside emacs.
Expected behaviour: opens an emacs buffer

the JULIA_EDITOR might be set in order to override the editor.

Another way would be to import Base.edit and override it maybe

**Comment by nico202** [comment]
I added this to my juliarc for now:

```julia
import Base.edit
edit(path::AbstractString, line::Integer=0) = println("file at " * join([path,line], ":"))```

**Comment by tpapp** [comment]
The editor needs to be set in Julia. Try
```julia
ENV["EDITOR"] = "emacsclient"
```
in your `~/.juliarc.jl`.

I will make a note to update the README to reflect this.

**Comment by non-Jedi** [comment]
Can't the package just automatically send `ENV["JULIA_EDITOR"] = "emacsclient"`
as the first command to the repl when it starts? I can't imagine a circumstance
where someone would want `EDITOR` as something else, but `"emacsclient"` could
be a user-overrideable default if we really wanted to keep that configurable.

Since the package taps directly into julia's `@edit`, it makes sense to me that
we might bind the package more tightly there as a convenience.
