### ISSUE TITLE
interrupt a running computation

### ISSUE THREAD

**Issue by gdkrmr** [tpapp/julia-repl#27]
Is it possible to interrupt a running computation? I tried C-c C-c (that is what works in ESS) and `term-interrupt-subjob` both did not work.

**Comment by tpapp** [comment]
Try `C-x C-c`. I should probably document this.

**Comment by gdkrmr** [comment]
that ist `term-send-raw`? doesn't work, a `^C` appears, but the process does not get interrupted, the same as `term-interrupt-subjob`.

**Comment by gdkrmr** [comment]
btw `C-x C-c` is a pretty dangerous key binding as it is usually used to exit emacs.

**Comment by tpapp** [comment]
Regarding the original issue: I feel that sending a `C-c` is the best `julia-repl` can do. It is true that sometimes Julia is not interrupted for a while, but AFAIK the same happens in a plain vanilla terminal and so that is an orthogonal issue.

Regarding the keybinding, I am open to suggestions. Eg I could change the escape char `C-x`, but it is convenient for other reasons.

**Comment by gdkrmr** [comment]
> Regarding the original issue: I feel that sending a C-c is the best julia-repl can do.

Agreed, the only other solution is to actually kill the job, which is not the job of `julia-repl` ;-), maybe a key binding to restart the process, but with `Revise` this is not really needed any more.

> Regarding the keybinding, I am open to suggestions. Eg I could change the escape char C-x, but it is convenient for other reasons.

I always liked `C-c C-c` from ess

**Comment by tpapp** [comment]
OK if I close this issue?

**Comment by AlexLewandowski** [comment]
I think `C-x C-c` should be changed to `C-c C-c`, which is more in-line with interrupts in term.

**Comment by AlexLewandowski** [comment]
At the very least make it something you can set within emacs.
