### ISSUE TITLE
how do I change the term to vterm?

### ISSUE THREAD

**Issue by nesteiner** [tpapp/julia-repl#94]
here I want to change the terminal of `julia-repl` into `vterm`, how do I do to modify your file?

**Comment by apparluk** [comment]
EmacsWiki [JuliaProgrammingLanguage](https://www.emacswiki.org/emacs/JuliaProgrammingLanguage)

The listed packages are written utilising different requires.

It's not possible to swap these correlated requires around which the specific package was written. 

julia-mode.el
;;; julia-mode.el --- Major mode for editing Julia source code -*- lexical-binding: t -*-

(require 'comint)

julia-repl.el
;;; julia-repl.el --- A minor mode for a Julia REPL -*- lexical-binding:t -*-

(require 'term)

julia-repl-vterm.el
;; julia-repl-vterm.el --- A mode for Julia REPL using vterm -*- lexical-binding: t -*-

(require 'vterm)

NB: The last listing depends on [emacs-libvterm](https://github.com/akermu/emacs-libvterm).

**Comment by tpapp** [comment]
Note that that code snippet with vterm is unsupported by this package.

If you are interested in using vterm, see #84. It is almost ready to merge except that there is an issue in the libvterm backend causing segfaults when clicking on source locations; because of this I am reluctant to merge (yet).
